export interface EdenModel {
  /** Provider key used in Eden AI API, e.g. "openai" */
  provider: string;
  /** Model name within the provider, passed in settings.{provider}.model */
  modelId: string | null;
  displayName: string;
  providerLabel: string;
  /** USD per 1M input tokens */
  inputCostPer1M: number;
  /** USD per 1M output tokens */
  outputCostPer1M: number;
  contextWindow: number;
  tier: "free" | "cheap" | "mid" | "premium";
}

/** Generation parameters for LLM calls */
export interface GenerationParams {
  temperature?: number; // 0.0 - 2.0, default ~0.7
  top_p?: number; // 0.0 - 1.0, default ~1.0
  top_k?: number; // 1+, default ~50
  max_tokens?: number; // max output length
  frequency_penalty?: number; // -2.0 to 2.0
  presence_penalty?: number; // -2.0 to 2.0
}

/** Key used in Eden AI API requests: "provider" or "provider/modelId" */
export function edenProviderKey(model: EdenModel): string {
  return model.provider;
}

/** Settings block for a specific model selection */
export function edenSettings(models: EdenModel[]): Record<string, string> {
  const hasModelId = (model: EdenModel): model is EdenModel & { modelId: string } =>
    model.modelId !== null;

  return Object.fromEntries(models.filter(hasModelId).map((m) => [m.provider, m.modelId]));
}

export const EDEN_MODELS: EdenModel[] = [
  // ── OpenAI ───────────────────────────────────────────────
  {
    provider: "openai",
    modelId: "gpt-4o-mini",
    displayName: "GPT-4o Mini",
    providerLabel: "OpenAI",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "openai",
    modelId: "gpt-4o",
    displayName: "GPT-4o",
    providerLabel: "OpenAI",
    inputCostPer1M: 5.0,
    outputCostPer1M: 15.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "openai",
    modelId: "gpt-3.5-turbo",
    displayName: "GPT-3.5 Turbo",
    providerLabel: "OpenAI",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 16_385,
    tier: "cheap",
  },
  {
    provider: "openai",
    modelId: "o1-mini",
    displayName: "o1 Mini (reasoning)",
    providerLabel: "OpenAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 12.0,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "openai",
    modelId: "gpt-4.1",
    displayName: "GPT-4.1",
    providerLabel: "OpenAI",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "openai",
    modelId: "gpt-4.1-mini",
    displayName: "GPT-4.1 Mini",
    providerLabel: "OpenAI",
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.6,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "openai",
    modelId: "gpt-4.1-nano",
    displayName: "GPT-4.1 Nano",
    providerLabel: "OpenAI",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "openai",
    modelId: "gpt-5",
    displayName: "GPT-5",
    providerLabel: "OpenAI",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 272_000,
    tier: "premium",
  },
  {
    provider: "openai",
    modelId: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    providerLabel: "OpenAI",
    inputCostPer1M: 0.25,
    outputCostPer1M: 2.0,
    contextWindow: 272_000,
    tier: "cheap",
  },
  {
    provider: "openai",
    modelId: "gpt-5-nano",
    displayName: "GPT-5 Nano",
    providerLabel: "OpenAI",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.4,
    contextWindow: 272_000,
    tier: "cheap",
  },
  {
    provider: "openai",
    modelId: "gpt-5-pro",
    displayName: "GPT-5 Pro",
    providerLabel: "OpenAI",
    inputCostPer1M: 15.0,
    outputCostPer1M: 120.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "openai",
    modelId: "o1",
    displayName: "o1",
    providerLabel: "OpenAI",
    inputCostPer1M: 15.0,
    outputCostPer1M: 60.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "openai",
    modelId: "o3-mini",
    displayName: "o3 Mini",
    providerLabel: "OpenAI",
    inputCostPer1M: 1.1,
    outputCostPer1M: 4.4,
    contextWindow: 200_000,
    tier: "mid",
  },
  {
    provider: "openai",
    modelId: "o3",
    displayName: "o3",
    providerLabel: "OpenAI",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "openai",
    modelId: "o4-mini",
    displayName: "o4 Mini",
    providerLabel: "OpenAI",
    inputCostPer1M: 1.1,
    outputCostPer1M: 4.4,
    contextWindow: 200_000,
    tier: "mid",
  },

  // ── Anthropic ────────────────────────────────────────────
  {
    provider: "anthropic",
    modelId: "claude-3-haiku-20240307",
    displayName: "Claude 3 Haiku",
    providerLabel: "Anthropic",
    inputCostPer1M: 0.25,
    outputCostPer1M: 1.25,
    contextWindow: 200_000,
    tier: "cheap",
  },
  {
    provider: "anthropic",
    modelId: "claude-3-5-haiku-20241022",
    displayName: "Claude 3.5 Haiku",
    providerLabel: "Anthropic",
    inputCostPer1M: 1.0,
    outputCostPer1M: 5.0,
    contextWindow: 200_000,
    tier: "mid",
  },
  {
    provider: "anthropic",
    modelId: "claude-3-5-sonnet-20241022",
    displayName: "Claude 3.5 Sonnet",
    providerLabel: "Anthropic",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    providerLabel: "Anthropic",
    inputCostPer1M: 1.0,
    outputCostPer1M: 5.0,
    contextWindow: 200_000,
    tier: "mid",
  },
  {
    provider: "anthropic",
    modelId: "claude-haiku-4-5-20251001",
    displayName: "Claude Haiku 4.5 (2025-10-01)",
    providerLabel: "Anthropic",
    inputCostPer1M: 1.0,
    outputCostPer1M: 5.0,
    contextWindow: 200_000,
    tier: "mid",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-1",
    displayName: "Claude Opus 4.1",
    providerLabel: "Anthropic",
    inputCostPer1M: 15.0,
    outputCostPer1M: 75.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    providerLabel: "Anthropic",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-sonnet-4-20250514",
    displayName: "Claude Sonnet 4",
    providerLabel: "Anthropic",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    providerLabel: "Anthropic",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-1-20250805",
    displayName: "Claude Opus 4.1 (2025-08-05)",
    providerLabel: "Anthropic",
    inputCostPer1M: 15.0,
    outputCostPer1M: 75.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-20250514",
    displayName: "Claude Opus 4 (2025-05-14)",
    providerLabel: "Anthropic",
    inputCostPer1M: 15.0,
    outputCostPer1M: 75.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-5-20251101",
    displayName: "Claude Opus 4.5 (2025-11-01)",
    providerLabel: "Anthropic",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    providerLabel: "Anthropic",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-7",
    displayName: "Claude Opus 4.7",
    providerLabel: "Anthropic",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "anthropic",
    modelId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    providerLabel: "Anthropic",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },

  // ── Google ───────────────────────────────────────────────
  {
    provider: "google",
    modelId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    providerLabel: "Google",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.5,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    providerLabel: "Google",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    providerLabel: "Google",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "google",
    modelId: "gemini-2.5-flash-lite",
    displayName: "Gemini 2.5 Flash Lite",
    providerLabel: "Google",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-2.0-flash-001",
    displayName: "Gemini 2.0 Flash 001",
    providerLabel: "Google",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-2.0-flash-lite-001",
    displayName: "Gemini 2.0 Flash Lite 001",
    providerLabel: "Google",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.3,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemma-3-4b-it",
    displayName: "Gemma 3 4B",
    providerLabel: "Google",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.08,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemma-3-12b-it",
    displayName: "Gemma 3 12B",
    providerLabel: "Google",
    inputCostPer1M: 0.09,
    outputCostPer1M: 0.29,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemma-3-27b-it",
    displayName: "Gemma 3 27B",
    providerLabel: "Google",
    inputCostPer1M: 0.23,
    outputCostPer1M: 0.38,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-2.5-computer-use-preview-10-2025",
    displayName: "Gemini 2.5 Computer Use Preview",
    providerLabel: "Google",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "google",
    modelId: "gemini-2.5-flash-image",
    displayName: "Gemini 2.5 Flash Image",
    providerLabel: "Google",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.5,
    contextWindow: 33_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-2.5-pro-preview-tts",
    displayName: "Gemini 2.5 Pro Preview TTS",
    providerLabel: "Google",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "google",
    modelId: "gemini-flash-latest",
    displayName: "Gemini Flash Latest",
    providerLabel: "Google",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.5,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-flash-lite-latest",
    displayName: "Gemini Flash Lite Latest",
    providerLabel: "Google",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemini-pro-latest",
    displayName: "Gemini Pro Latest",
    providerLabel: "Google",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "google",
    modelId: "gemma-4-26b-a4b-it",
    displayName: "Gemma 4 26B A4B",
    providerLabel: "Google",
    inputCostPer1M: 0.01,
    outputCostPer1M: 0.01,
    contextWindow: 262_000,
    tier: "cheap",
  },
  {
    provider: "google",
    modelId: "gemma-4-31b-it",
    displayName: "Gemma 4 31B",
    providerLabel: "Google",
    inputCostPer1M: 0.01,
    outputCostPer1M: 0.01,
    contextWindow: 262_000,
    tier: "cheap",
  },

  // ── Bytedance ────────────────────────────────────────────
  {
    provider: "bytedance",
    modelId: "seed-1-6-250915",
    displayName: "Seed 1.6 250915",
    providerLabel: "Bytedance",
    inputCostPer1M: 0.25,
    outputCostPer1M: 2.0,
    contextWindow: 256_000,
    tier: "mid",
  },
  {
    provider: "bytedance",
    modelId: "seed-2-0-lite-260228",
    displayName: "Seed 2.0 Lite 260228",
    providerLabel: "Bytedance",
    inputCostPer1M: 0.25,
    outputCostPer1M: 2.0,
    contextWindow: 256_000,
    tier: "mid",
  },
  {
    provider: "bytedance",
    modelId: "seed-2-0-mini-260215",
    displayName: "Seed 2.0 Mini 260215",
    providerLabel: "Bytedance",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    contextWindow: 256_000,
    tier: "cheap",
  },
  {
    provider: "bytedance",
    modelId: "seed-2-0-pro-260328",
    displayName: "Seed 2.0 Pro 260328",
    providerLabel: "Bytedance",
    inputCostPer1M: 0.5,
    outputCostPer1M: 3.0,
    contextWindow: 256_000,
    tier: "premium",
  },

  // ── Cerebras ─────────────────────────────────────────────
  {
    provider: "cerebras",
    modelId: "llama3.1-8b",
    displayName: "Llama 3.1 8B",
    providerLabel: "Cerebras",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.1,
    contextWindow: 128_000,
    tier: "cheap",
  },

  // ── Cloudflare ───────────────────────────────────────────
  {
    provider: "cloudflare",
    modelId: "@cf/meta/llama-2-7b-chat-fp16",
    displayName: "Llama 2 7B Chat FP16",
    providerLabel: "Cloudflare",
    inputCostPer1M: 1.92,
    outputCostPer1M: 1.92,
    contextWindow: 3_000,
    tier: "cheap",
  },
  {
    provider: "cloudflare",
    modelId: "@cf/meta/llama-2-7b-chat-int8",
    displayName: "Llama 2 7B Chat INT8",
    providerLabel: "Cloudflare",
    inputCostPer1M: 1.92,
    outputCostPer1M: 1.92,
    contextWindow: 2_000,
    tier: "cheap",
  },
  {
    provider: "cloudflare",
    modelId: "@cf/mistral/mistral-7b-instruct-v0.1",
    displayName: "Mistral 7B Instruct v0.1",
    providerLabel: "Cloudflare",
    inputCostPer1M: 1.92,
    outputCostPer1M: 1.92,
    contextWindow: 8_000,
    tier: "cheap",
  },
  {
    provider: "cloudflare",
    modelId: "@hf/thebloke/codellama-7b-instruct-awq",
    displayName: "CodeLlama 7B Instruct AWQ",
    providerLabel: "Cloudflare",
    inputCostPer1M: 1.92,
    outputCostPer1M: 1.92,
    contextWindow: 4_000,
    tier: "cheap",
  },

  // ── Databricks ───────────────────────────────────────────
  {
    provider: "databricks",
    modelId: "databricks-gpt-oss-120b",
    displayName: "Databricks GPT OSS 120B",
    providerLabel: "Databricks",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "databricks",
    modelId: "databricks-gpt-oss-20b",
    displayName: "Databricks GPT OSS 20B",
    providerLabel: "Databricks",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.3,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "databricks",
    modelId: "databricks-gpt-5",
    displayName: "Databricks GPT 5",
    providerLabel: "Databricks",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 272_000,
    tier: "premium",
  },
  {
    provider: "databricks",
    modelId: "databricks-gpt-5-mini",
    displayName: "Databricks GPT 5 Mini",
    providerLabel: "Databricks",
    inputCostPer1M: 0.25,
    outputCostPer1M: 2.0,
    contextWindow: 272_000,
    tier: "cheap",
  },
  {
    provider: "databricks",
    modelId: "databricks-gpt-5-nano",
    displayName: "Databricks GPT 5 Nano",
    providerLabel: "Databricks",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.4,
    contextWindow: 272_000,
    tier: "cheap",
  },

  // ── Amazon ───────────────────────────────────────────────
  {
    provider: "amazon",
    modelId: "amazon.nova-micro-v1:0",
    displayName: "Nova Micro",
    providerLabel: "Amazon",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.14,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "amazon.nova-lite-v1:0",
    displayName: "Nova Lite",
    providerLabel: "Amazon",
    inputCostPer1M: 0.06,
    outputCostPer1M: 0.24,
    contextWindow: 300_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "amazon.nova-pro-v1:0",
    displayName: "Nova Pro",
    providerLabel: "Amazon",
    inputCostPer1M: 0.8,
    outputCostPer1M: 3.2,
    contextWindow: 300_000,
    tier: "premium",
  },

  // ── Mistral ──────────────────────────────────────────────
  {
    provider: "mistral",
    modelId: "mistral-small-latest",
    displayName: "Mistral Small",
    providerLabel: "Mistral",
    inputCostPer1M: 0.06,
    outputCostPer1M: 0.18,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "mistral",
    modelId: "mistral-large-latest",
    displayName: "Mistral Large",
    providerLabel: "Mistral",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 262_000,
    tier: "premium",
  },
  {
    provider: "mistral",
    modelId: "mistral-medium-latest",
    displayName: "Mistral Medium",
    providerLabel: "Mistral",
    inputCostPer1M: 0.4,
    outputCostPer1M: 2.0,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "mistral",
    modelId: "magistral-small-latest",
    displayName: "Magistral Small",
    providerLabel: "Mistral",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 40_000,
    tier: "cheap",
  },
  {
    provider: "mistral",
    modelId: "magistral-medium-latest",
    displayName: "Magistral Medium",
    providerLabel: "Mistral",
    inputCostPer1M: 2.0,
    outputCostPer1M: 5.0,
    contextWindow: 40_000,
    tier: "mid",
  },
  {
    provider: "mistral",
    modelId: "devstral-small-2507",
    displayName: "Devstral Small",
    providerLabel: "Mistral",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.3,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "mistral",
    modelId: "devstral-medium-2507",
    displayName: "Devstral Medium",
    providerLabel: "Mistral",
    inputCostPer1M: 0.4,
    outputCostPer1M: 2.0,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "mistral",
    modelId: "open-mistral-nemo",
    displayName: "Open Mistral Nemo",
    providerLabel: "Mistral",
    inputCostPer1M: 0.3,
    outputCostPer1M: 0.3,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "mistral",
    modelId: "open-mixtral-8x7b",
    displayName: "Open Mixtral 8x7B",
    providerLabel: "Mistral",
    inputCostPer1M: 0.4,
    outputCostPer1M: 0.4,
    contextWindow: 131_000,
    tier: "cheap",
  },

  // ── Cohere ───────────────────────────────────────────────
  {
    provider: "cohere",
    modelId: "command-r",
    displayName: "Command R",
    providerLabel: "Cohere",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "cohere",
    modelId: "command-r7b-12-2024",
    displayName: "Command R 7B",
    providerLabel: "Cohere",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.04,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "cohere",
    modelId: "command-r-plus-08-2024",
    displayName: "Command R+",
    providerLabel: "Cohere",
    inputCostPer1M: 2.5,
    outputCostPer1M: 10.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "cohere",
    modelId: "command-a-03-2025",
    displayName: "Command A",
    providerLabel: "Cohere",
    inputCostPer1M: 2.5,
    outputCostPer1M: 10.0,
    contextWindow: 256_000,
    tier: "premium",
  },
  {
    provider: "cohere",
    modelId: "command",
    displayName: "Command",
    providerLabel: "Cohere",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "cohere",
    modelId: "command-light",
    displayName: "Command Light",
    providerLabel: "Cohere",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "cohere",
    modelId: "command-nightly",
    displayName: "Command Nightly",
    providerLabel: "Cohere",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "cohere",
    modelId: "command-light-nightly",
    displayName: "Command Light Nightly",
    providerLabel: "Cohere",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128_000,
    tier: "cheap",
  },

  // ── Meta / Llama (via Groq on Eden AI) ──────────────────
  {
    provider: "meta",
    modelId: "llama3-1-8b-instruct-v1:0",
    displayName: "Llama 3.1 8B Instruct",
    providerLabel: "Meta",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.08,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "meta",
    modelId: "llama3-1-70b-instruct-v1:0",
    displayName: "Llama 3.1 70B Instruct",
    providerLabel: "Meta",
    inputCostPer1M: 0.59,
    outputCostPer1M: 0.79,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "meta",
    modelId: "llama3-1-405b-instruct-v1:0",
    displayName: "Llama 3.1 405B Instruct",
    providerLabel: "Meta",
    inputCostPer1M: 0.27,
    outputCostPer1M: 0.81,
    contextWindow: 8_192,
    tier: "premium",
  },

  // ── Additional Amazon catalog entries ────────────────────
  {
    provider: "amazon",
    modelId: "ai21.jamba-1-5-mini-v1:0",
    displayName: "Jamba 1.5 Mini",
    providerLabel: "Amazon",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.4,
    contextWindow: 256_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "ai21.jamba-1-5-large-v1:0",
    displayName: "Jamba 1.5 Large",
    providerLabel: "Amazon",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 256_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "anthropic.claude-3-haiku-20240307-v1:0",
    displayName: "Claude 3 Haiku",
    providerLabel: "Amazon",
    inputCostPer1M: 0.25,
    outputCostPer1M: 1.25,
    contextWindow: 200_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "anthropic.claude-3-sonnet-20240229-v1:0",
    displayName: "Claude 3 Sonnet",
    providerLabel: "Amazon",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "cohere.command-r-v1:0",
    displayName: "Command R",
    providerLabel: "Amazon",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "cohere.command-r-plus-v1:0",
    displayName: "Command R+",
    providerLabel: "Amazon",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "deepseek.v3.2",
    displayName: "DeepSeek V3.2",
    providerLabel: "Amazon",
    inputCostPer1M: 0.62,
    outputCostPer1M: 1.85,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "google.gemma-3-4b-it",
    displayName: "Gemma 3 4B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.08,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "google.gemma-3-12b-it",
    displayName: "Gemma 3 12B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.09,
    outputCostPer1M: 0.29,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "google.gemma-3-27b-it",
    displayName: "Gemma 3 27B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.23,
    outputCostPer1M: 0.38,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "minimax.minimax-m2",
    displayName: "MiniMax M2",
    providerLabel: "Amazon",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "minimax.minimax-m2.1",
    displayName: "MiniMax M2.1",
    providerLabel: "Amazon",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 196_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "minimax.minimax-m2.5",
    displayName: "MiniMax M2.5",
    providerLabel: "Amazon",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.devstral-2-123b",
    displayName: "Devstral 2 123B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.4,
    outputCostPer1M: 2.0,
    contextWindow: 256_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "mistral.magistral-small-2509",
    displayName: "Magistral Small 2509",
    providerLabel: "Amazon",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.ministral-3-14b-instruct",
    displayName: "Ministral 3 14B Instruct",
    providerLabel: "Amazon",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.2,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.ministral-3-3b-instruct",
    displayName: "Ministral 3 3B Instruct",
    providerLabel: "Amazon",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.1,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.ministral-3-8b-instruct",
    displayName: "Ministral 3 8B Instruct",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.15,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.mistral-7b-instruct-v0:2",
    displayName: "Mistral 7B Instruct",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.2,
    contextWindow: 32_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.mistral-large-2402-v1:0",
    displayName: "Mistral Large 2402",
    providerLabel: "Amazon",
    inputCostPer1M: 8.0,
    outputCostPer1M: 24.0,
    contextWindow: 32_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "mistral.mistral-large-3-675b-instruct",
    displayName: "Mistral Large 3 675B Instruct",
    providerLabel: "Amazon",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "mistral.mistral-small-2402-v1:0",
    displayName: "Mistral Small 2402",
    providerLabel: "Amazon",
    inputCostPer1M: 1.0,
    outputCostPer1M: 3.0,
    contextWindow: 32_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.mixtral-8x7b-instruct-v0:1",
    displayName: "Mixtral 8x7B Instruct",
    providerLabel: "Amazon",
    inputCostPer1M: 0.45,
    outputCostPer1M: 0.7,
    contextWindow: 32_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.voxtral-mini-3b-2507",
    displayName: "Voxtral Mini 3B 2507",
    providerLabel: "Amazon",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.04,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "mistral.voxtral-small-24b-2507",
    displayName: "Voxtral Small 24B 2507",
    providerLabel: "Amazon",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.3,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "moonshotai.kimi-k2.5",
    displayName: "Kimi K2.5",
    providerLabel: "Amazon",
    inputCostPer1M: 0.6,
    outputCostPer1M: 3.03,
    contextWindow: 262_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "moonshot.kimi-k2-thinking",
    displayName: "Kimi K2 Thinking",
    providerLabel: "Amazon",
    inputCostPer1M: 0.6,
    outputCostPer1M: 2.5,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "nvidia.nemotron-nano-12b-v2",
    displayName: "Nemotron Nano 12B v2",
    providerLabel: "Amazon",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "nvidia.nemotron-nano-3-30b",
    displayName: "Nemotron Nano 3 30B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.06,
    outputCostPer1M: 0.24,
    contextWindow: 262_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "nvidia.nemotron-nano-9b-v2",
    displayName: "Nemotron Nano 9B v2",
    providerLabel: "Amazon",
    inputCostPer1M: 0.06,
    outputCostPer1M: 0.23,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "nvidia.nemotron-super-3-120b",
    displayName: "Nemotron Super 3 120B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.65,
    contextWindow: 256_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "openai.gpt-oss-120b-1:0",
    displayName: "GPT-OSS 120B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "openai.gpt-oss-20b-1:0",
    displayName: "GPT-OSS 20B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.3,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "openai.gpt-oss-safeguard-120b",
    displayName: "GPT-OSS Safeguard 120B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "openai.gpt-oss-safeguard-20b",
    displayName: "GPT-OSS Safeguard 20B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.2,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "qwen.qwen3-32b-v1:0",
    displayName: "Qwen3 32B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "qwen.qwen3-coder-30b-a3b-v1:0",
    displayName: "Qwen3 Coder 30B A3B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 262_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "qwen.qwen3-coder-next",
    displayName: "Qwen3 Coder Next",
    providerLabel: "Amazon",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.2,
    contextWindow: 262_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "qwen.qwen3-next-80b-a3b",
    displayName: "Qwen3 Next 80B A3B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.15,
    outputCostPer1M: 1.2,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "qwen.qwen3-vl-235b-a22b",
    displayName: "Qwen3 VL 235B A22B",
    providerLabel: "Amazon",
    inputCostPer1M: 0.53,
    outputCostPer1M: 2.66,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "amazon",
    modelId: "zai.glm-4.7",
    displayName: "GLM 4.7",
    providerLabel: "Amazon",
    inputCostPer1M: 0.6,
    outputCostPer1M: 2.2,
    contextWindow: 200_000,
    tier: "mid",
  },
  {
    provider: "amazon",
    modelId: "zai.glm-4.7-flash",
    displayName: "GLM 4.7 Flash",
    providerLabel: "Amazon",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.4,
    contextWindow: 200_000,
    tier: "cheap",
  },
  {
    provider: "amazon",
    modelId: "zai.glm-5",
    displayName: "GLM 5",
    providerLabel: "Amazon",
    inputCostPer1M: 1.0,
    outputCostPer1M: 3.2,
    contextWindow: 200_000,
    tier: "premium",
  },

  // ── DeepInfra / Deepseek / Groq / Fireworks / others ─────
  {
    provider: "deepinfra",
    modelId: "anthropic/claude-3-7-sonnet-latest",
    displayName: "Claude 3.7 Sonnet",
    providerLabel: "DeepInfra",
    inputCostPer1M: 3.3,
    outputCostPer1M: 16.5,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "anthropic/claude-4-opus",
    displayName: "Claude 4 Opus",
    providerLabel: "DeepInfra",
    inputCostPer1M: 16.5,
    outputCostPer1M: 82.5,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "anthropic/claude-4-sonnet",
    displayName: "Claude 4 Sonnet",
    providerLabel: "DeepInfra",
    inputCostPer1M: 3.3,
    outputCostPer1M: 16.5,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-R1-0528",
    displayName: "DeepSeek R1 0528",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.5,
    outputCostPer1M: 2.15,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-R1-0528-Turbo",
    displayName: "DeepSeek R1 0528 Turbo",
    providerLabel: "DeepInfra",
    inputCostPer1M: 1.0,
    outputCostPer1M: 3.0,
    contextWindow: 33_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    displayName: "DeepSeek R1 Distill Llama 70B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-V3",
    displayName: "DeepSeek V3",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.38,
    outputCostPer1M: 0.89,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-V3-0324",
    displayName: "DeepSeek V3 0324",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.25,
    outputCostPer1M: 0.88,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-V3.1",
    displayName: "DeepSeek V3.1",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.27,
    outputCostPer1M: 1.0,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "deepseek-ai/DeepSeek-V3.1-Terminus",
    displayName: "DeepSeek V3.1 Terminus",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.27,
    outputCostPer1M: 1.0,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "google/gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.5,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "google/gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    providerLabel: "DeepInfra",
    inputCostPer1M: 1.25,
    outputCostPer1M: 10.0,
    contextWindow: 1_000_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "google/gemma-3-12b-it",
    displayName: "Gemma 3 12B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.1,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "google/gemma-3-27b-it",
    displayName: "Gemma 3 27B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.09,
    outputCostPer1M: 0.16,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "google/gemma-3-4b-it",
    displayName: "Gemma 3 4B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.08,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "meta-llama/Llama-3.1-70B-Instruct-Turbo",
    displayName: "Llama 3.1 70B Turbo",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.28,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "meta-llama/Llama-3.1-8B-Instruct-Turbo",
    displayName: "Llama 3.1 8B Turbo",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.02,
    outputCostPer1M: 0.03,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "meta-llama/Meta-Llama-3.1-70B-Instruct",
    displayName: "Meta Llama 3.1 70B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.4,
    outputCostPer1M: 0.4,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "meta-llama/Meta-Llama-3.1-8B-Instruct",
    displayName: "Meta Llama 3.1 8B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.03,
    outputCostPer1M: 0.05,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "mistralai/Mistral-Nemo-Instruct-2407",
    displayName: "Mistral Nemo Instruct",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.02,
    outputCostPer1M: 0.04,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "mistralai/Mistral-Small-24B-Instruct-2501",
    displayName: "Mistral Small 24B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.08,
    contextWindow: 33_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
    displayName: "Mistral Small 3.2 24B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.2,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    displayName: "Mixtral 8x7B Instruct",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.4,
    outputCostPer1M: 0.4,
    contextWindow: 33_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen2.5-72B-Instruct",
    displayName: "Qwen 2.5 72B Instruct",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.12,
    outputCostPer1M: 0.39,
    contextWindow: 33_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-14B",
    displayName: "Qwen 3 14B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.06,
    outputCostPer1M: 0.24,
    contextWindow: 41_000,
    tier: "cheap",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    displayName: "Qwen 3 235B A22B Instruct",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.09,
    outputCostPer1M: 0.6,
    contextWindow: 262_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    displayName: "Qwen 3 235B A22B Thinking",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.9,
    contextWindow: 262_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-30B-A3B",
    displayName: "Qwen 3 30B A3B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.08,
    outputCostPer1M: 0.29,
    contextWindow: 41_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-32B",
    displayName: "Qwen 3 32B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.28,
    contextWindow: 41_000,
    tier: "mid",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    displayName: "Qwen 3 Coder 480B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.6,
    contextWindow: 262_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo",
    displayName: "Qwen 3 Coder 480B Turbo",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.29,
    outputCostPer1M: 1.2,
    contextWindow: 262_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    displayName: "Qwen 3 Next 80B",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.14,
    outputCostPer1M: 1.4,
    contextWindow: 262_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Sao10K/L3.1-70B-Euryale-v2.2",
    displayName: "L3.1 70B Euryale v2.2",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.65,
    outputCostPer1M: 0.75,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Sao10K/L3.3-70B-Euryale-v2.3",
    displayName: "L3.3 70B Euryale v2.3",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.65,
    outputCostPer1M: 0.75,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "deepinfra",
    modelId: "Sao10K/L3-8B-Lunaris-v1-Turbo",
    displayName: "L3 8B Lunaris Turbo",
    providerLabel: "DeepInfra",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.05,
    contextWindow: 8_192,
    tier: "cheap",
  },
  {
    provider: "deepseek",
    modelId: "deepseek-chat",
    displayName: "DeepSeek Chat",
    providerLabel: "DeepSeek",
    inputCostPer1M: 0.28,
    outputCostPer1M: 0.42,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "deepseek",
    modelId: "deepseek-reasoner",
    displayName: "DeepSeek Reasoner",
    providerLabel: "DeepSeek",
    inputCostPer1M: 0.28,
    outputCostPer1M: 0.42,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "fireworks",
    modelId: "accounts/fireworks/models/deepseek-v3p1",
    displayName: "DeepSeek V3.1",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.56,
    outputCostPer1M: 1.68,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "fireworks",
    modelId: "accounts/fireworks/models/deepseek-v3p2",
    displayName: "DeepSeek V3.2",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.56,
    outputCostPer1M: 1.68,
    contextWindow: 164_000,
    tier: "mid",
  },
  {
    provider: "fireworks",
    modelId: "accounts/fireworks/models/gpt-oss-120b",
    displayName: "GPT OSS 120B",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "fireworks",
    modelId: "accounts/fireworks/models/kimi-k2p5",
    displayName: "Kimi K2.5",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.6,
    outputCostPer1M: 3.0,
    contextWindow: 262_000,
    tier: "mid",
  },
  {
    provider: "fireworks",
    modelId: "glm-4p7",
    displayName: "GLM 4.7",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.6,
    outputCostPer1M: 2.2,
    contextWindow: 203_000,
    tier: "mid",
  },
  {
    provider: "fireworks",
    modelId: "kimi-k2p5",
    displayName: "Kimi K2.5",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.6,
    outputCostPer1M: 3.0,
    contextWindow: 262_000,
    tier: "mid",
  },
  {
    provider: "fireworks",
    modelId: "minimax-m2p1",
    displayName: "MiniMax M2.1",
    providerLabel: "Fireworks",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 205_000,
    tier: "cheap",
  },
  {
    provider: "groq",
    modelId: "llama-3.1-8b-instant",
    displayName: "Llama 3.1 8B Instant",
    providerLabel: "Groq",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.08,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "groq",
    modelId: "llama-3.3-70b-versatile",
    displayName: "Llama 3.3 70B Versatile",
    providerLabel: "Groq",
    inputCostPer1M: 0.59,
    outputCostPer1M: 0.79,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "groq",
    modelId: "meta-llama/llama-4-scout-17b-16e-instruct",
    displayName: "Llama 4 Scout 17B",
    providerLabel: "Groq",
    inputCostPer1M: 0.11,
    outputCostPer1M: 0.34,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "groq",
    modelId: "openai/gpt-oss-120b",
    displayName: "GPT OSS 120B",
    providerLabel: "Groq",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "groq",
    modelId: "openai/gpt-oss-20b",
    displayName: "GPT OSS 20B",
    providerLabel: "Groq",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.3,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "groq",
    modelId: "openai/gpt-oss-safeguard-20b",
    displayName: "GPT OSS Safeguard 20B",
    providerLabel: "Groq",
    inputCostPer1M: 0.07,
    outputCostPer1M: 0.3,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "groq",
    modelId: "qwen/qwen3-32b",
    displayName: "Qwen3 32B",
    providerLabel: "Groq",
    inputCostPer1M: 0.29,
    outputCostPer1M: 0.59,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "microsoft",
    modelId: "gpt-35-turbo",
    displayName: "GPT-35 Turbo",
    providerLabel: "Microsoft",
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    contextWindow: 4_096,
    tier: "cheap",
  },
  {
    provider: "microsoft",
    modelId: "gpt-35-turbo-16k",
    displayName: "GPT-35 Turbo 16K",
    providerLabel: "Microsoft",
    inputCostPer1M: 3.0,
    outputCostPer1M: 4.0,
    contextWindow: 16_384,
    tier: "cheap",
  },
  {
    provider: "microsoft",
    modelId: "gpt-4",
    displayName: "GPT-4",
    providerLabel: "Microsoft",
    inputCostPer1M: 30.0,
    outputCostPer1M: 60.0,
    contextWindow: 8_192,
    tier: "premium",
  },
  {
    provider: "microsoft",
    modelId: "gpt-4o",
    displayName: "GPT-4o",
    providerLabel: "Microsoft",
    inputCostPer1M: 2.5,
    outputCostPer1M: 10.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "microsoft",
    modelId: "gpt-4o-mini",
    displayName: "GPT-4o Mini",
    providerLabel: "Microsoft",
    inputCostPer1M: 0.17,
    outputCostPer1M: 0.66,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "microsoft",
    modelId: "o1-mini",
    displayName: "o1 Mini",
    providerLabel: "Microsoft",
    inputCostPer1M: 1.21,
    outputCostPer1M: 4.84,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "microsoft",
    modelId: "o3-mini",
    displayName: "o3 Mini",
    providerLabel: "Microsoft",
    inputCostPer1M: 1.1,
    outputCostPer1M: 4.4,
    contextWindow: 200_000,
    tier: "mid",
  },
  {
    provider: "minimax",
    modelId: "minimax-m1",
    displayName: "MiniMax M1",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.4,
    outputCostPer1M: 2.2,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "minimax",
    modelId: "MiniMax-M2",
    displayName: "MiniMax M2",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 200_000,
    tier: "cheap",
  },
  {
    provider: "minimax",
    modelId: "MiniMax-M2.1",
    displayName: "MiniMax M2.1",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "minimax",
    modelId: "MiniMax-M2.1-lightning",
    displayName: "MiniMax M2.1 Lightning",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.4,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "minimax",
    modelId: "MiniMax-M2.5",
    displayName: "MiniMax M2.5",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.3,
    outputCostPer1M: 1.2,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "minimax",
    modelId: "MiniMax-M2.5-lightning",
    displayName: "MiniMax M2.5 Lightning",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.3,
    outputCostPer1M: 2.4,
    contextWindow: 1_000_000,
    tier: "cheap",
  },
  {
    provider: "minimax",
    modelId: "minimax-text-01",
    displayName: "MiniMax Text 01",
    providerLabel: "MiniMax",
    inputCostPer1M: 0.2,
    outputCostPer1M: 1.1,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "ovhcloud",
    modelId: "gpt-oss-120b",
    displayName: "GPT OSS 120B",
    providerLabel: "OVHcloud",
    inputCostPer1M: 0.08,
    outputCostPer1M: 0.4,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "ovhcloud",
    modelId: "gpt-oss-20b",
    displayName: "GPT OSS 20B",
    providerLabel: "OVHcloud",
    inputCostPer1M: 0.04,
    outputCostPer1M: 0.15,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "ovhcloud",
    modelId: "Llama-3.1-8B-Instruct",
    displayName: "Llama 3.1 8B Instruct",
    providerLabel: "OVHcloud",
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.1,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "ovhcloud",
    modelId: "Meta-Llama-3_3-70B-Instruct",
    displayName: "Llama 3.3 70B Instruct",
    providerLabel: "OVHcloud",
    inputCostPer1M: 0.67,
    outputCostPer1M: 0.67,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "perplexityai",
    modelId: "sonar",
    displayName: "Sonar",
    providerLabel: "Perplexity",
    inputCostPer1M: 1.0,
    outputCostPer1M: 1.0,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "perplexityai",
    modelId: "sonar-deep-research",
    displayName: "Sonar Deep Research",
    providerLabel: "Perplexity",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "perplexityai",
    modelId: "sonar-pro",
    displayName: "Sonar Pro",
    providerLabel: "Perplexity",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 200_000,
    tier: "premium",
  },
  {
    provider: "perplexityai",
    modelId: "sonar-reasoning-pro",
    displayName: "Sonar Reasoning Pro",
    providerLabel: "Perplexity",
    inputCostPer1M: 2.0,
    outputCostPer1M: 8.0,
    contextWindow: 128_000,
    tier: "premium",
  },
  {
    provider: "together",
    modelId: "google/gemma-4-31B-it",
    displayName: "Gemma 4 31B",
    providerLabel: "Together",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.5,
    contextWindow: 262_000,
    tier: "cheap",
  },
  {
    provider: "together",
    modelId: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    displayName: "Llama 3.3 70B Turbo",
    providerLabel: "Together",
    inputCostPer1M: 0.88,
    outputCostPer1M: 0.88,
    contextWindow: 128_000,
    tier: "mid",
  },
  {
    provider: "together",
    modelId: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    displayName: "Mixtral 8x7B Instruct",
    providerLabel: "Together",
    inputCostPer1M: 0.6,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "together",
    modelId: "openai/gpt-oss-120b",
    displayName: "GPT OSS 120B",
    providerLabel: "Together",
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    contextWindow: 131_000,
    tier: "mid",
  },
  {
    provider: "together",
    modelId: "openai/gpt-oss-20b",
    displayName: "GPT OSS 20B",
    providerLabel: "Together",
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.2,
    contextWindow: 128_000,
    tier: "cheap",
  },
  {
    provider: "xai",
    modelId: "grok-3",
    displayName: "Grok 3",
    providerLabel: "xAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-3-beta",
    displayName: "Grok 3 Beta",
    providerLabel: "xAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-3-fast-beta",
    displayName: "Grok 3 Fast Beta",
    providerLabel: "xAI",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-3-fast-latest",
    displayName: "Grok 3 Fast Latest",
    providerLabel: "xAI",
    inputCostPer1M: 5.0,
    outputCostPer1M: 25.0,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-3-latest",
    displayName: "Grok 3 Latest",
    providerLabel: "xAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 131_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-3-mini-fast",
    displayName: "Grok 3 Mini Fast",
    providerLabel: "xAI",
    inputCostPer1M: 0.6,
    outputCostPer1M: 4.0,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "xai",
    modelId: "grok-3-mini-fast-beta",
    displayName: "Grok 3 Mini Fast Beta",
    providerLabel: "xAI",
    inputCostPer1M: 0.6,
    outputCostPer1M: 4.0,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "xai",
    modelId: "grok-3-mini-fast-latest",
    displayName: "Grok 3 Mini Fast Latest",
    providerLabel: "xAI",
    inputCostPer1M: 0.6,
    outputCostPer1M: 4.0,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "xai",
    modelId: "grok-3-mini-latest",
    displayName: "Grok 3 Mini Latest",
    providerLabel: "xAI",
    inputCostPer1M: 0.3,
    outputCostPer1M: 0.5,
    contextWindow: 131_000,
    tier: "cheap",
  },
  {
    provider: "xai",
    modelId: "grok-4",
    displayName: "Grok 4",
    providerLabel: "xAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 256_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-4-0709",
    displayName: "Grok 4 0709",
    providerLabel: "xAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 256_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-4-fast-non-reasoning",
    displayName: "Grok 4 Fast Non-Reasoning",
    providerLabel: "xAI",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.5,
    contextWindow: 2_000_000,
    tier: "mid",
  },
  {
    provider: "xai",
    modelId: "grok-4-fast-reasoning",
    displayName: "Grok 4 Fast Reasoning",
    providerLabel: "xAI",
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.5,
    contextWindow: 2_000_000,
    tier: "mid",
  },
  {
    provider: "xai",
    modelId: "grok-4-latest",
    displayName: "Grok 4 Latest",
    providerLabel: "xAI",
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    contextWindow: 256_000,
    tier: "premium",
  },
  {
    provider: "xai",
    modelId: "grok-code-fast",
    displayName: "Grok Code Fast",
    providerLabel: "xAI",
    inputCostPer1M: 0.2,
    outputCostPer1M: 1.5,
    contextWindow: 256_000,
    tier: "cheap",
  },
];

export const PROVIDER_ORDER = [
  "openai",
  "amazon",
  "anthropic",
  "google",
  "bytedance",
  "cerebras",
  "cloudflare",
  "databricks",
  "deepinfra",
  "deepseek",
  "fireworks",
  "groq",
  "microsoft",
  "minimax",
  "mistral",
  "ovhcloud",
  "perplexityai",
  "together",
  "xai",
  "cohere",
  "meta",
];

export function groupByProvider(models: EdenModel[]): Record<string, EdenModel[]> {
  return models.reduce<Record<string, EdenModel[]>>((acc, m) => {
    if (!acc[m.provider]) acc[m.provider] = [];
    acc[m.provider].push(m);
    return acc;
  }, {});
}

export const TIER_LABELS: Record<EdenModel["tier"], string> = {
  free: "Bezpłatny",
  cheap: "Tani",
  mid: "Średni",
  premium: "Premium",
};

export function formatCost(usd: number): string {
  if (usd === 0) return "bezpłatny";
  if (usd < 0.01) return `$${usd.toFixed(4)}`;
  return `$${usd.toFixed(2)}`;
}
